# Generated by Django 4.2.1 on 2023-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="chat_id",
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
