# Generated by Django 4.2.1 on 2023-08-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_notification_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="chat_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
