# Generated by Django 4.2.1 on 2023-08-03 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_notification_chat_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
