# Generated by Django 4.2.4 on 2023-08-12 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "HARD"), ("SOFT", "SOFT")], max_length=20
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1,
                                message="Amount of books can not be 0 or negative number",
                            )
                        ]
                    ),
                ),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
