# Generated by Django 4.2.1 on 2023-07-31 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(
                verbose_name=django.core.validators.MinValueValidator(
                    limit_value=1,
                    message="Amount of books can not be 0 or negative number",
                )
            ),
        ),
    ]
