# Generated by Django 4.2.1 on 2023-07-31 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=1,
                        message="Amount of books can not be 0 or negative number",
                    )
                ]
            ),
        ),
    ]
